---
dependency:
  name: galaxy
  enabled: false

driver:
  name: docker

provisioner:
  name: ansible
  playbooks:
    cleanup: ../shared/cleanup.yml
    converge: ../shared/converge.yml
    prepare: ../shared/prepare.yml

verifier:
  name: testinfra
  directory: ../shared/tests/
